// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Template = 1,
  InsertBlock = 2,
  InsertBlockStart = 3,
  ExpressionContent = 4,
  InsertBlockContent = 5,
  InsertBlockEnd = 6,
  InsertBlockEof = 7,
  PlainText = 8
