// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!^QQOPOOOOOO'#C_'#C_OYOQO'#C^OOOO'#Ce'#CeQQOPOOOOOO'#C`'#C`OeOQO'#C`OOOO,58x,58xOOOO-E6c-E6cOOOO,58z,58z",
  stateData: "o~OWROZPO~OTUOUTOVTO~OUXOVXO~OW~",
  goto: "lYPPZ_cPPPPfTROSTQOSRVQQSORWS",
  nodeNames: "⚠ Template InsertBlock InsertBlockStart ExpressionContent InsertBlockContent InsertBlockEnd InsertBlockEof PlainText",
  maxTerm: 11,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "#V~RTO#ob#o#p!h#p;'Sb;'S;=`!]<%lOb~gTW~O#ob#o#pv#p;'Sb;'S;=`!]<%lOb~yUO#ob#p;'Sb;'S;=`!]<%l~b~Ob~~!c~!`P;=`<%lb~!hOW~~!kVO#ob#o#p#Q#p;'Sb;'S;=`!]<%l~b~Ob~~!c~#VOZ~",
  tokenizers: [1, new LocalTokenGroup("j~RQ#q#rX~~d~[P#q#r_~dOU~~iOV~~", 25, 5)],
  topRules: {"Template":[0,1]},
  tokenPrec: 29
})
